import Image from 'next/image'
import { ArrowUpRight,Cpu,Lightbulb,PlugZap,Settings2 } from 'lucide-react'
import Reveal from './Reveal'
const items=[
  {title:'Instalações Elétricas',desc:'Projetos e instalações residenciais, comerciais e industriais.',image:'/images/service-installation.svg',Icon:PlugZap},
  {title:'Automação Elétrica',desc:'Mais conforto, tecnologia e praticidade para o seu dia.',image:'/images/service-automation.svg',Icon:Cpu},
  {title:'Iluminação Residencial e Comercial',desc:'Projetos que valorizam e economizam energia.',image:'/images/service-lighting.svg',Icon:Lightbulb},
  {title:'Soluções Completas',desc:'Do planejamento à execução. Tudo em um só lugar.',image:'/images/service-complete.svg',Icon:Settings2}]
export default function Services(){return <section id="servicos" className="section-pad grid-lines bg-ink"><div className="shell"><div className="mb-14 grid gap-7 lg:grid-cols-[1.5fr_.6fr] lg:items-end"><Reveal><div className="eyebrow">Nossos serviços</div><h2 className="display max-w-4xl text-5xl sm:text-6xl lg:text-7xl">Soluções elétricas<br/><span className="text-gold">completas</span> para você</h2></Reveal><Reveal delay={.15}><p className="border-l border-gold/50 pl-6 text-sm leading-7 text-white/50">Da instalação à automação, entregamos segurança, eficiência e qualidade em cada detalhe.</p></Reveal></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{items.map(({title,desc,image,Icon},i)=><Reveal key={title} delay={i*.08}><article className="group relative h-[470px] overflow-hidden border border-white/10 bg-coal transition duration-500 hover:border-gold/60 hover:shadow-[0_0_30px_rgba(243,195,22,.08)]"><Image src={image} alt={title} fill sizes="(max-width:768px) 100vw,25vw" className="object-cover transition duration-700 group-hover:scale-[1.04]"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/60 to-black/5 transition group-hover:via-black/45"/><div className="absolute inset-x-0 bottom-0 p-7"><span className="mb-6 flex h-11 w-11 items-center justify-center bg-gold text-ink"><Icon size={20}/></span><h3 className="font-display text-xl font-bold uppercase leading-tight">{title}</h3><p className="mt-3 min-h-12 text-xs leading-6 text-white/55">{desc}</p><a href="#contato" className="mt-6 inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-gold transition group-hover:translate-x-1">Saiba mais <ArrowUpRight size={14}/></a></div></article></Reveal>)}</div></div></section>}
